title: Cooper's Site
author: Cooper
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 This is my awesome site where I post awesome stuff done by me or perharps other awesome people, given permission, of course
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
